micronaut:
  application:
    name: github-actions-micronaut-demo
datasources:
  default:
    url: ${DATASOURCES_DEFAULT_URL:`jdbc:oracle:thin:@demodb_LOW?TNS_ADMIN=/wallet`}
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: cicd
    password: ${DATASOURCES_DEFAULT_PASSWORD}
    schema-generate: NONE
    dialect: ORACLE
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'