name: micronaut-ci-demo
on:
  push:
    branches:
      - master
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        env:
          FOO: bar
        run: |
          echo "Starting the build job. Foo is $FOO."

      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'Write OCI Config File'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
          echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
      - name: 'Write Public Key'
        run: |
          echo "${{secrets.OCI_PUBLIC_KEY}}" >> ~/.oci/id_oci_demo.pub
      - name: 'List Instances'
        run: |
          ./gradlew listInstances \
              --availability-domain odti:PHX-AD-1 \
              --compartment-id ocid1.compartment.oc1..aaaaaaaa7lzppsdxt6j56zhpvy6u5gyrenwyc2e2h4fak5ydvv6kt7anizbq

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Assemble JAR'
        run: |
          ./gradlew assemble

      - name: 'Run Tests'
        run: |
          ./gradlew test

      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/test/*

      - name: 'Get Version Number'
        run: |
          echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'github-actions-micronaut-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar

      - name: 'Create Instance'
        run: |
          ./gradlew setupInstance \
            --compartment-id=ocid1.compartment.oc1..aaaaaaaa7lzppsdxt6j56zhpvy6u5gyrenwyc2e2h4fak5ydvv6kt7anizbq \
            --verbose \
            --instance-name=github-actions-micronaut-demo-${{env.VERSION}}-${date +%d_%m_%Y_%H_%M_%S} \
            --image=java-11-custom-image \
            --shape=VM.Standard2.1 \
            --public-key-file=~/.oci/id_oci_demo.pub