name: micronaut-ci-demo
on:
  push:
    branches:
      - master
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        env:
          FOO: bar
        run: |
          echo "Starting the build job. Foo is $FOO."

      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'Write OCI Config File'
        run: |
          mkdir ~/.oci
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
          echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem

      - name: 'Write Public Key & User Data File'
        run: |
          touch /home/runner/cloud-init.sh
          echo "${{secrets.OCI_PUBLIC_KEY}}" >> /home/runner/.oci/id_oci_demo.pub

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Run Tests'
        run: |
          ./gradlew test

      - name: 'Assemble JAR'
        run: |
          ./gradlew assemble

      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/test/*

      - name: 'Get Version Number'
        run: |
          echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'github-actions-micronaut-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar

      - name: 'Create Instance'
        run: |
          ./gradlew step01 \
            -Doci.compartment.id=ocid1.compartment.oc1..aaaaaaaa7lzppsdxt6j56zhpvy6u5gyrenwyc2e2h4fak5ydvv6kt7anizbq \
            -Doci.instance.name=actions1 \
            -PpublicKeyFile=/home/runner/.oci/id_oci_demo.pub \
            -PuserDataFile=/home/runner/cloud-init.sh

      - name: 'Temp'
        run: |
          more build/oci/instance/actions1.properties
          function prop {
              grep "${1}" build/oci/instance/actions1.properties|cut -d'=' -f2
          }
          echo "yo..."
          echo $(prop 'vcn.security-list.id')
          export SEC_LIST_ID=$(prop 'vcn.security-list.id')
          export IP=$(prop 'instance.public-ip.0')
          echo "::set-env name=SECURITY_LIST_ID::$SEC_LIST_ID"
          echo "::set-env name=IP_ADDRESS::$IP"

      - name: 'Add Ingress Rule'
        run: |
          ./gradlew addIngressSecurityRule \
            --destination-port=8080 \
            --security-list-id=${{env.SECURITY_LIST_ID}}

      - name: 'Stop App'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP_ADDRESS }}
          username: opc
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
              pid=`ps aux | grep "[g]ithub-actions-micronaut-demo*" | awk '{print $2}'`
              if [ "$pid" == "" ]; then
                echo "Process not found"
              else
                kill -9 $pid
              fi
              sudo mkdir -p /app

      - name: 'Push JAR'
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.IP_ADDRESS }}
          username: opc
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          source: "build/libs/github-actions-micronaut-demo-${{env.VERSION}}-all.jar"
          target: "/app/github-actions-micronaut-demo.jar"

      - name: 'Start App'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP_ADDRESS }}
          username: opc
          key: ${{ secrets.OCI_INSTANCE_PRIVATE_KEY }}
          script: |
            java -jar /app/github-actions-micronaut-demo.jar