name: micronaut-ci-demo
on:
  push:
    branches:
      - master
jobs:
  demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:
      - name: 'Step One'
        uses: actions/hello_world@master
        with:
          first_name: Todd
      - name: 'Gradle Assemble'
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build