name: micronaut-ci-demo
on:
  push:
    branches:
      - master
jobs:
  demo-job:
    name: Demo Job
    runs-on: ubuntu-latest
    steps:

      - name: 'Step One'
        env:
          FOO: bar
        run: |
          echo "Step One. Foo is $FOO."

      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Assemble'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble

      - name 'Publish'
        uses: actions/upload-artifact@v1
          with:
            name: github-actions-micronaut-demo.jar
            path: path/to/artifact